"""
Pydantic schemas for request validation and response serialization.

All schemas include OpenAPI examples for Swagger UI documentation.
"""

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, Field


# ── Single Audio Record ──────────────────────────────────────────────

class AudioRecordSchema(BaseModel):
    """A single audio record stored in the pipeline database."""

    id: int = Field(..., description="Unique record identifier", examples=[1])
    device_id: str = Field(..., description="Wearable device that uploaded this audio", examples=["device_101"])
    file_path: str = Field(
        ...,
        description="Relative path to the stored audio file",
        examples=["audio_storage/device_101/20260312_181500_a1b2c3d4_recording.wav"],
    )
    file_name: str = Field(..., description="Original uploaded filename", examples=["recording.wav"])
    file_size: int = Field(..., description="File size in bytes", examples=[64044])
    duration: Optional[float] = Field(None, description="Audio duration in seconds", examples=[2.5])
    transcription: Optional[str] = Field(
        None,
        description="Text transcription generated by Faster-Whisper",
        examples=["Hello, this is a test recording from the wearable device."],
    )
    language: Optional[str] = Field(
        None,
        description="Detected language code (ISO 639-1)",
        examples=["en"],
    )
    language_confidence: Optional[float] = Field(
        None,
        description="Language detection confidence score (0.0 to 1.0)",
        examples=[0.9856],
    )
    created_at: datetime = Field(
        ...,
        description="Upload timestamp (UTC)",
        examples=["2026-03-12T18:15:00"],
    )

    model_config = {
        "from_attributes": True,
        "json_schema_extra": {
            "examples": [
                {
                    "id": 1,
                    "device_id": "device_101",
                    "file_path": "audio_storage/device_101/20260312_181500_a1b2c3d4_recording.wav",
                    "file_name": "recording.wav",
                    "file_size": 64044,
                    "duration": 2.5,
                    "transcription": "Hello, this is a test recording from the wearable device.",
                    "language": "en",
                    "language_confidence": 0.9856,
                    "created_at": "2026-03-12T18:15:00",
                }
            ]
        },
    }


# ── Upload Response ──────────────────────────────────────────────────

class AudioUploadResponse(BaseModel):
    """Response returned after a successful audio upload and transcription."""

    id: int = Field(..., description="Newly created record ID", examples=[1])
    device_id: str = Field(..., description="Device that uploaded the audio", examples=["device_101"])
    file_name: str = Field(..., description="Original uploaded filename", examples=["recording.wav"])
    file_size: int = Field(..., description="Saved file size in bytes", examples=[64044])
    duration: Optional[float] = Field(None, description="Audio duration in seconds", examples=[2.5])
    transcription: Optional[str] = Field(
        None,
        description="Faster-Whisper transcription output",
        examples=["Hello, this is a test recording from the wearable device."],
    )
    language: Optional[str] = Field(
        None,
        alias="detected_language",
        description="Detected language code — e.g. 'en' (English), 'hi' (Hindi)",
        examples=["en"],
    )
    language_confidence: Optional[float] = Field(
        None,
        description="Confidence of language detection (0.0 to 1.0, where 1.0 = certain)",
        examples=[0.9856],
    )
    created_at: datetime = Field(
        ...,
        description="Upload timestamp (UTC)",
        examples=["2026-03-12T18:15:00"],
    )

    model_config = {
        "from_attributes": True,
        "populate_by_name": True,
        "json_schema_extra": {
            "examples": [
                {
                    "id": 1,
                    "device_id": "device_101",
                    "file_name": "recording.wav",
                    "file_size": 64044,
                    "duration": 2.5,
                    "transcription": "Hello, this is a test recording from the wearable device.",
                    "detected_language": "en",
                    "language_confidence": 0.9856,
                    "created_at": "2026-03-12T18:15:00",
                },
                {
                    "id": 2,
                    "device_id": "device_202",
                    "file_name": "hindi_sample.wav",
                    "file_size": 128088,
                    "duration": 4.0,
                    "transcription": "नमस्ते, यह एक टेस्ट रिकॉर्डिंग है।",
                    "detected_language": "hi",
                    "language_confidence": 0.9432,
                    "created_at": "2026-03-12T18:20:00",
                },
            ]
        },
    }


# ── Device Audio List Response ───────────────────────────────────────

class DeviceAudioResponse(BaseModel):
    """Paginated list of all audio records for a specific wearable device."""

    device_id: str = Field(..., description="Queried device identifier", examples=["device_101"])
    total_records: int = Field(..., description="Total number of records for this device", examples=[3])
    records: List[AudioRecordSchema] = Field(..., description="Audio records (paginated, newest first)")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "device_id": "device_101",
                    "total_records": 2,
                    "records": [
                        {
                            "id": 2,
                            "device_id": "device_101",
                            "file_path": "audio_storage/device_101/20260312_181600_b2c3d4e5_recording_002.wav",
                            "file_name": "recording_002.wav",
                            "file_size": 80044,
                            "duration": 2.5,
                            "transcription": "Second recording from device one hundred one.",
                            "language": "en",
                            "language_confidence": 0.9912,
                            "created_at": "2026-03-12T18:16:00",
                        },
                        {
                            "id": 1,
                            "device_id": "device_101",
                            "file_path": "audio_storage/device_101/20260312_181500_a1b2c3d4_recording_001.wav",
                            "file_name": "recording_001.wav",
                            "file_size": 64044,
                            "duration": 2.0,
                            "transcription": "Hello, this is the first test recording.",
                            "language": "en",
                            "language_confidence": 0.9856,
                            "created_at": "2026-03-12T18:15:00",
                        },
                    ],
                }
            ]
        }
    }
